title: ⚽ livegoal_90
logo:  # you can add own logo.
description: ⚽ livegoal_90 é un bot ideato per rilasciare pronostici calcistici durante lo svolgimento delle partite.
baseurl: "/live" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com


# Author Settings
author:
  name: livegoal_90
  image: '/assets/img/20200114_131328_0000.png'
  job: Ricercatore di profitto
  bio: 
  email: livegoal90@gmail.com


# Contact links
contact:
  - name: Telegram
    link: http://t.me/livegoal_90
  - name: Instagram
    link: https://instagram.com/


# Comment Section (Disqus)
disqus-identifier: lg90 # add your shortname for Disqus Comment. For example mr-brown


# Google Analytics
google-analytics: # add your identifier. For example UA-99631805-1.


# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-sitemap
  - jekyll/tagging

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir:         tag
tag_page_layout:      tag-page
tag_permalink_style:  pretty

sass:
  sass_dir: _sass
  style: compressed


# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
